// Code generated by cmd/gents; DO NOT EDIT.
// Regenerate: go run ./cmd/gents (in practocore-backend/deadlineengine)
// Source of truth: the Go wire types of the deadline engine.

/** ISO date string (YYYY-MM-DD); null when an optional date is unset. */
export type CivilDate = string | null;

export type Status = "pending" | "resolved" | "fulfilled" | "inactive" | "missed";
export type EventType = "FULFILL_EVENT" | "FULFILL" | "ADJOURN" | "RECALCULATE" | "SPAWN" | "CORRECT" | "MISS";
export type FieldType = "text" | "number" | "bool" | "select" | "date";
export type DeadlineKind = "offset" | "fixed" | "recurring";
export type DependencyKind = "ref" | "switch" | "earliestOf" | "latestOf";
export type TogglerAction = "activate" | "deactivate";

export interface DslValue {
  Type: number;
  Num: number;
  Str: string;
  Bool: boolean;
  Date: CivilDate;
}

export interface CountingRules {
  CountWeekends: boolean;
  CountHolidays: boolean;
  CountRecesses: boolean;
}

export interface TraceStep {
  Date: CivilDate;
  Kind: number;
  Action: number;
  Remaining: number;
}

export interface OffsetTrace {
  Start: CivilDate;
  Offset: number;
  Counting: CountingRules;
  Shift: number;
  PreLanding: CivilDate;
  Final: CivilDate;
  Steps: TraceStep[];
}

export interface ResolvedEvent {
  id: string;
  label: string;
  fulfilled: boolean;
  date?: CivilDate;
}

export interface ResolvedDeadline {
  id: string;
  baseId: string;
  partyId?: string;
  label: string;
  kind: string;
  active: boolean;
  resolved: boolean;
  fulfilled: boolean;
  adjourned: boolean;
  missed?: boolean;
  status: Status;
  date?: CivilDate;
  window?: boolean;
  earliest?: CivilDate;
  latest?: CivilDate;
  chosenRef?: string;
  dependencyAt?: CivilDate;
  matchedBranch: number;
  trace?: OffsetTrace;
}

export interface MatterEvent {
  seq: number;
  type: EventType;
  target?: string;
  date?: CivilDate;
  actorId?: string;
  supersedes?: number;
}

export interface Party {
  id: string;
  roleId: string;
  eventDates?: Record<string, CivilDate>;
}

export interface Schedule {
  templateVersion: string;
  calendarVersion: string;
  jurisdiction: string;
  triggerId: string;
  trigger: CivilDate;
  fields: Record<string, DslValue>;
  events: Record<string, ResolvedEvent>;
  deadlines: Record<string, ResolvedDeadline>;
  order: string[];
  parties?: Party[];
}

export interface Explanation {
  deadlineId: string;
  label: string;
  templateVersion: string;
  calendarVersion: string;
  status: Status;
  trigger: CivilDate;
  chosenRef?: string;
  matchedBranch: number;
  dependencyAt?: CivilDate;
  date?: CivilDate;
  window?: boolean;
  earliest?: CivilDate;
  latest?: CivilDate;
  adjourned: boolean;
  trace?: OffsetTrace;
}

export interface ValidationIssue {
  code: string;
  path: string;
  msg: string;
}

export interface ValidationResult {
  errors: ValidationIssue[];
  warnings: ValidationIssue[];
}

export interface TriggerSpec {
  id: string;
  label: string;
  prompt?: string;
}

export interface TemplateField {
  id: string;
  label: string;
  type: FieldType;
  options?: string[];
  required: boolean;
}

export interface Toggler {
  when: string;
  target: string;
  action: TogglerAction;
}

export interface EventPrompts {
  input?: string;
  fulfilled?: string;
}

export interface DeadlinePrompts {
  input?: string;
  pending?: string;
  fulfilled?: string;
  overdue?: string;
}

export interface TemplateMilestone {
  id: string;
  label: string;
  prompts?: EventPrompts;
  togglers?: Toggler[];
}

export interface SwitchBranch {
  when: string;
  then: string;
}

export interface DependencySpec {
  kind: DependencyKind;
  ref?: string;
  branches?: SwitchBranch[];
  else?: string;
  refs?: string[];
}

export interface OffsetSpec {
  window: boolean;
  value?: number;
  valueExpr?: string;
  min?: number;
  max?: number;
}

export interface LandingSpec {
  forbidden?: string[];
  shift?: string;
}

export interface Recurrence {
  everyDays?: number;
  everyMonths?: number;
  untilEvent?: string;
  untilDate?: CivilDate;
  untilCount?: number;
}

export interface ReminderSpec {
  id: string;
  label: string;
  daysBefore: number;
  title?: string;
  body?: string;
  bodyHTML?: string;
}

export interface OnMiss {
  togglers?: Toggler[];
}

export interface TemplateDeadline {
  id: string;
  label: string;
  kind: DeadlineKind;
  partyScope?: string;
  dynamic: boolean;
  activeWhen?: string;
  dependency?: DependencySpec;
  offset?: OffsetSpec;
  counting?: CountingRules;
  landing?: LandingSpec;
  fixedDate?: CivilDate;
  fixedDateExpr?: string;
  recurrence?: Recurrence;
  reminders?: ReminderSpec[];
  togglers?: Toggler[];
  onMiss?: OnMiss;
  prompts?: DeadlinePrompts;
  disableFulfill?: boolean;
}

export interface PartyRole {
  id: string;
  label: string;
  min: number;
  max: number;
  representationRequired: boolean;
}

export interface TemplateIR {
  name: string;
  jurisdiction: string;
  trigger: TriggerSpec;
  fields?: TemplateField[];
  events?: TemplateMilestone[];
  deadlines?: TemplateDeadline[];
  partyRoles?: PartyRole[];
}

